# can be configured globally
# [proxy]
# http = "http://squid:3128"

[sources.nginx]
type = "nginx_metrics"
endpoints = [ "http://nginx/basic_status" ]
scrape_interval_secs = 15

[sources.nginx.proxy]
http = "http://squid:3128"

[sinks.console]
type = "console"
inputs = [ "nginx" ]
target = "stdout"

[sinks.console.encoding]
codec = "json"
timestamp_format = "rfc3339"
