replicas: 3
# The Vector Aggregator chart defines a
# vector source that is made available to you.
# You do not need to define a log source.
transforms:
  # Adjust as necessary. This remap transform parses a JSON
  # formatted log message, emitting a log if the contents are
  # not valid JSON
  # /docs/reference/transforms/
  remap:
    type: remap
    inputs: ["vector"]
    source: |
      structured, err = parse_json(.message)
      if err != null {
        log("Unable to parse JSON: " + err, level: "error")
      } else {
        . = merge(., object!(structured))
      }      
sinks:
  # Adjust as necessary. By default we use the console sink
  # to print all data. This allows you to see Vector working.
  # /docs/reference/sinks/
  stdout:
    type: console
    inputs: ["remap"]
    target: "stdout"
    encoding: "json"
