[sources.logs]
type = "generator"
format = "json"
interval = 2

[transforms.tag]
type = "remap"
inputs = ["logs"]
source = '''
.tag = "http_logs"
'''

[sinks.out]
type = "vector"
inputs = ["tag"]
address = "aggregator:9000"
version = "2"

[sinks.out.healthcheck]
enabled = true
