[api]
enabled = true
address = "0.0.0.0:8686"

[sources.in]
type = "vector"
address = "0.0.0.0:9000"
version = "2"

[sinks.out]
type = "console"
inputs = ["in"]
target = "stdout"

[sinks.out.encoding]
codec = "json"