[api]
enabled = true
address = "0.0.0.0:8686"
playground = true

[sources.generator]
type = "generator"
format = "json"
interval = 0.5

[sinks.stdout]
type = "console"
inputs = ["generator"]
target = "stdout"

[sinks.stdout.encoding]
codec = "json"

[sources.vector_logs]
type = "internal_logs"

[sources.vector_metrics]
type = "internal_metrics"

[transforms.tag_vector_logs]
type = "remap"
inputs = ["vector_logs"]
source = '''
.tag = "vector"
'''

[sinks.datadog_logs]
type = "datadog_logs"
inputs = ["tag_vector_logs"]
default_api_key = "${DD_API_KEY}"

[sinks.datadog_logs.healthcheck]
enabled = true

[sinks.datadog_logs.encoding]
codec = "json"

[sinks.datadog_metrics]
type = "datadog_metrics"
inputs = ["vector_metrics"]
api_key = "${DD_API_KEY}"

[sinks.datadog_metrics.healthcheck]
enabled = true
