version: '3.8'
services:
  http_logs_agent:
    image: timberio/vector:nightly-alpine
    deploy:
      replicas: 5
    volumes:
      - ./vector/agent/http:/etc/vector:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - aggregator
  syslog_logs_agent:
    image: timberio/vector:nightly-alpine
    deploy:
      replicas: 5
    volumes:
      - ./vector/agent/syslog:/etc/vector:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - aggregator
  aggregator:
    container_name: aggregator
    image: timberio/vector:nightly-alpine
    ports:
      - 9000:9000
    environment:
      - LOG=info
    volumes:
      - ./vector/aggregator:/etc/vector:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
