version: '3.8'
services:
  http_logs_agent:
    image: timberio/vector:nightly-alpine
    deploy:
      replicas: 3
    volumes:
      - ./vector/agent/http:/etc/vector:ro
    depends_on:
      - aggregator
  transaction_logs_agent:
    image: timberio/vector:nightly-alpine
    deploy:
      replicas: 3
    volumes:
      - ./vector/agent/transaction:/etc/vector:ro
    depends_on:
      - aggregator
  syslog_logs_agent:
    image: timberio/vector:nightly-alpine
    deploy:
      replicas: 3
    volumes:
      - ./vector/agent/syslog:/etc/vector:ro
    depends_on:
      - aggregator
  fluentbit_agent:
    image: fluent/fluent-bit:1.8
    deploy:
      replicas: 3
    volumes:
      - ./fluent-bit:/fluent-bit/etc:ro
  aggregator:
    container_name: aggregator
    image: timberio/vector:nightly-alpine
    ports:
      - 8686:8686
      - 9000:9000
      - 24224:24224
    environment:
      - LOG=info
    volumes:
      - ./vector/aggregator:/etc/vector:ro
