datadog:
  logLevel: debug
  clusterName: vector-demo
  logs:
    containerCollectAll: true
    enabled: true
  orchestratorExplorer:
    enabled: true
  processAgent:
    processCollection: true
  prometheusScrape:
    enabled: true
agents:
  useConfigMap: true
  customAgentConfig:
    logs_config:
      logs_dd_url: "vector.mycompany.tld:8080"
      logs_no_ssl: true
      use_http: true
      use_v2_api: false
