datadog:
  clusterName: vector-demo
  logs:
    containerCollectAll: true
    enabled: true
  orchestratorExplorer:
    enabled: true
  processAgent:
    processCollection: true
  prometheusScrape:
    enabled: true
agents:
  useConfigMap: true
  customAgentConfig:
    logs_config:
      logs_dd_url: "internal-k8s-vector-vector-e67b4af534-965797666.us-east-1.elb.amazonaws.com:8080"
      logs_no_ssl: true
      use_http: true
      use_v2_api: false
