role: Stateless-Aggregator

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 256Mi

env:
  - name: DATADOG_API_KEY
    valueFrom:
      secretKeyRef:
        name: vector
        key: DATADOG_API_KEY

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9090"

customConfig:
  api:
    enabled: true
    address: 0.0.0.0:8686
  sources:
    datadog_agents:
      type: datadog_agent
      acknowledgements: true
      address: 0.0.0.0:8080
    internal_metrics:
      type: internal_metrics
  transforms:
    add_tags:
      type: remap
      inputs:
        - datadog_agents
      source: |
        .ddtags = parse_key_value!(.ddtags, key_value_delimiter: ":", field_delimiter: ",")
        .ddtags.sender = "vector"
        .ddtags.vector_aggregator = get_hostname!()
        .ddtags = encode_key_value(.ddtags, key_value_delimiter: ":", field_delimiter: ",")

        parsed =
          parse_json(.message) ??
          parse_syslog(.message) ??
          {}
        . = merge(., object!(parsed))
  sinks:
    to_datadog:
      type: datadog_logs
      inputs:
        - add_tags
      default_api_key: "${DATADOG_API_KEY}"
      encoding:
        codec: json
    prom_exporter:
      type: prometheus_exporter
      inputs:
        - internal_metrics
      address: 0.0.0.0:9090
